version: '3'

services:
  prod_portfolio_app:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    volumes:
      - ../:/app
    networks:
      - hofi_network

networks:
  hofi_network:
    external: true