version: '3'

services:
  prod_portfolio_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    ports:
      - "5000:5000"
    networks:
      - hofi_network

networks:
  hofi_network:
    external: true
